### ISSUE TITLE
missing numpy "include_dirs" in setup.py

### ISSUE THREAD

**Issue by beeondev** [MattShannon/bandmat#4]
Hi, 
I have done a package for the Gentoo distribution. Doing so, i have been forced to modify setup.py (and test_linalg.py). See the sed lines (line 27,28,29) in the following if you interested in 
[bandmat-0.5-r1.ebuild.txt](https://github.com/MattShannon/bandmat/files/1219681/bandmat-0.5-r1.ebuild.txt)

Best regards.

**Comment by MattShannon** [comment]
Sorry for the very slow reply! I'm thrilled to hear you packaged bandmat! That's fantastic. I think 2 of the 3 issues in your sed commands were already fixed in bandmat 0.6. I'll fix the exception "as e" issue.

**Comment by MattShannon** [comment]
The "as e" issue is fixed at head.
