### ISSUE TITLE
'-Wno-unused-but-set-variable' causes error during install

### ISSUE THREAD

**Issue by engiecat** [MattShannon/bandmat#7]
Hi.

I'm currently using Windows 10 with VS2017.
While installing bandmat via pip, '-Wno-unused-but-set-variable' is not recognized by the compiler, causing error during the installation. 

Commenting out the part in setup.py seems to alleviate the issue. (though with many warnings)

**Comment by beausoft** [comment]
I have this problem too.

**Comment by engiecat** [comment]
@beausoft 
https://github.com/MattShannon/bandmat/blob/aa58eaf8919760b786ccf91653a8902f229fdfc5/setup.py#L46-L60

comment out Line 49 and 57 did solve the problem and for now it works fine :)

**Comment by r9y9** [comment]
This should be fixed by #6 but unfortunately, @MattShannon doesn't seem to be on GitHub these days...

**Comment by IwraStudios** [comment]
@r9y9 You might want to email him: matt.shannon@cantab.net

**Comment by MattShannon** [comment]
Sorry, I've been meaning to sort this out for ages. I'll have a closer look. I use a darcs repo behind the scenes so my preference is to fix the windows build issues there rather than merging the outstanding PR. Thanks so much for the feedback and patience!

**Comment by MattShannon** [comment]
Windows builds should be fixed now. Please let me know if you experience any further issues.
